name: Package and release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Package and release
        uses: BigWigsMods/packager@e50a250f8705041e40f2fa1ddcb280a686d65aa0 # v2.6.1
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
